<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="dev.houston.servicetests.MinerServiceTestsMockito" tests="4" skipped="0" failures="0" errors="0" timestamp="2021-03-14T19:55:17" hostname="Troys-MBP" time="0.276">
  <properties/>
  <testcase name="get_miner_by_user_pass_invalid()" classname="dev.houston.servicetests.MinerServiceTestsMockito" time="0.263"/>
  <testcase name="get_miner_by_user_pass_valid()" classname="dev.houston.servicetests.MinerServiceTestsMockito" time="0.004"/>
  <testcase name="get_miner_name_by_id()" classname="dev.houston.servicetests.MinerServiceTestsMockito" time="0.003"/>
  <testcase name="get_miner_by_user_pass_not_found()" classname="dev.houston.servicetests.MinerServiceTestsMockito" time="0.002"/>
  <system-out><![CDATA[ INFO [Test worker] (MinerServiceImpl.java:19) - mbitter
ERROR [Test worker] (MinerServiceImpl.java:24) - Invalid password for user: mbitter
 INFO [Test worker] (MinerServiceTestsMockito.java:67) - Invalid password
 INFO [Test worker] (MinerServiceImpl.java:19) - mbitter
 INFO [Test worker] (MinerServiceTestsMockito.java:56) - Miner 3 logged in
 INFO [Test worker] (MinerServiceTestsMockito.java:86) - Grimly Berrgson
 INFO [Test worker] (MinerServiceImpl.java:19) - test
 INFO [Test worker] (MinerServiceImpl.java:28) - No miner found with that username
 INFO [Test worker] (MinerServiceTestsMockito.java:78) - User not found
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
